# Generated by Django 3.0.1 on 2020-03-11 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bounce_points', models.IntegerField(default=10)),
                ('bounce_points_negative', models.IntegerField(default=0)),
                ('pounce_points', models.IntegerField(default=10)),
                ('pounce_points_negative', models.IntegerField(default=-10)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Quiz')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='quiz_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Quiz'),
            preserve_default=False,
        ),
    ]
